{
    "name"          : "Tutorial Odoo Indonesia",
    "version"       : "1.0",
    "author"        : "newbie",
    "website"       : "alisancatur.com",
    "category"      : "New Module",
    "summary"       : "Belajar Membuat Addons",
    "description"   : """
        Belajar membuat addons di odoo 10 menggunakan studi kasus puskesmas
    """,
    "depends"       : [
        "product",
        "account",
        "ptf_base",
    ],
    "data"          : [
        "views/res_partner.xml",
        "views/ptf_poli.xml",
        "views/ptf_pendaftaran.xml",
        "views/ptf_pemeriksaan.xml",
        "views/product_template.xml",
        "views/account_invoice.xml",
        "wizard/ptf_reason_cancel_wizard.xml",
        "report/report_resepobat.xml",
        "security/ir.model.access.csv",
    ],
    "demo"          : [],
    "test"          : [],
    "images"        : [],
    "qweb"          : [],
    "css"           : [],
    "application"   : True,
    "installable"   : True,
    "auto_install"  : False,
}
